version: '3.9'
services:
  postgres:
    image: 'postgres'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 8080
      POSTGRES_DB: mentormatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  postgres-data: 